CREATE OR ALTER PROCEDURE SP_CREATE_CENTER
(@EMAIL NVARCHAR(255), @NAME NVARCHAR(50), @ADDRESS NVARCHAR(150), @IMAGE NVARCHAR(MAX) = '', @TELEPHONE NVARCHAR(15))
AS
	--Generate new ID
	DECLARE @NEWID INT;
	SELECT @NEWID = MAX(CENTER_ID) + 1 FROM CENTER;
	--Insert new center
	INSERT INTO CENTER VALUES(@NEWID, @EMAIL, @NAME, @ADDRESS, @IMAGE, @TELEPHONE);
GO

CREATE OR ALTER PROCEDURE SP_UPDATE_CENTER
(@CENTERID INT, @EMAIL NVARCHAR(255), @NAME NVARCHAR(50), @ADDRESS NVARCHAR(150), @IMAGE NVARCHAR(MAX) = '', @TELEPHONE NVARCHAR(15))
AS
	UPDATE CENTER SET EMAIL = @EMAIL, NAME = @NAME, ADDRESS = @ADDRESS, IMAGE = @IMAGE, TELEPHONE = @TELEPHONE
	WHERE CENTER_ID = @CENTERID;
GO

CREATE OR ALTER PROCEDURE SP_DELETE_CENTER
(@CENTERID INT)
AS
	DELETE FROM CENTER WHERE CENTER_ID = @CENTERID;
GO