CREATE OR ALTER PROCEDURE SP_CREATE_CONTENT
(@CONTENT NVARCHAR(MAX), @GROUPCONTENT INT, @FILEID INT = '')
AS
	--Generate new ID
	DECLARE @NEWID INT;
	SELECT @NEWID = MAX(CONTENT_ID) + 1 FROM CONTENT;

	INSERT INTO CONTENT VALUES (@NEWID, @CONTENT, @GROUPCONTENT, @FILEID);
GO

CREATE OR ALTER PROCEDURE SP_DELETE_CONTENT
(@CONTENTID INT)
AS
	DELETE FROM CONTENT WHERE CONTENT_ID = @CONTENTID;
GO

CREATE OR ALTER PROCEDURE SP_UPDATE_CONTENT
(@CONTENTID INT, @CONTENT NVARCHAR(MAX))
AS
	UPDATE CONTENT SET CONTENT = @CONTENT
	WHERE CONTENT_ID = @CONTENTID;
GO