CREATE OR ALTER PROCEDURE SP_CREATE_COURSE
(@CENTER_ID INT, @NAME NVARCHAR(30), @DESCRIPTION NVARCHAR(350) = NULL, @IMAGE NVARCHAR(MAX) = NULL, @IS_VISIBLE BIT = 0, @COURSEID INT OUTPUT, @GROUPID INT OUTPUT)
AS
	DECLARE @COURSE_ID INT;

	--Insert the course
	SELECT @COURSE_ID = (MAX([COURSE].[COURSE_ID]) + 1) FROM [COURSE];

	IF (@COURSE_ID IS NULL) BEGIN
		SET @COURSE_ID = 0;
	END

	INSERT INTO COURSE VALUES
	(@COURSE_ID, GETDATE(), GETDATE(), @DESCRIPTION, @IMAGE, @NAME, @CENTER_ID, @IS_VISIBLE);

	-- Create a group for discussion
	DECLARE @GROUP_ID INT;
	SELECT @GROUP_ID = (MAX([GROUP].GROUP_ID) + 1) FROM [GROUP];

	IF (@GROUP_ID IS NULL) BEGIN
		SET @GROUP_ID = 0;
	END
	INSERT INTO [GROUP] VALUES (@GROUP_ID, @IMAGE, @NAME, @COURSE_ID);

	SET @COURSEID = @COURSE_ID;
	SET @GROUPID = @GROUP_ID;
GO

CREATE OR ALTER PROCEDURE SP_UPDATE_COURSE
(@COURSE_ID INT, @NAME NVARCHAR(30), @DESCRIPTION NVARCHAR(350) = NULL, @IMAGE NVARCHAR(MAX) = NULL)
AS
	UPDATE [COURSE] SET [NAME] = @NAME, [IMAGE] = @IMAGE, [DESCRIPTION] = @DESCRIPTION
	WHERE [COURSE].COURSE_ID = @COURSE_ID;
GO

CREATE OR ALTER PROCEDURE SP_DELETE_COURSE
(@COURSE_ID INT)
AS
	--Delete the course
	DELETE FROM COURSE WHERE COURSE_ID = @COURSE_ID;
GO

CREATE OR ALTER PROCEDURE SP_USER_COURSES
(@USER_ID INT)
AS
	SELECT C.COURSE_ID, C.DATE_PUBLISHED, C.DATE_MODIFIED, C.[DESCRIPTION], C.[IMAGE], C.[NAME], C.CENTER_ID 
	FROM COURSE C INNER JOIN USER_COURSE UC
	ON C.COURSE_ID = UC.COURSE_ID
	WHERE UC.[USER_ID] = @USER_ID;
GO
